
title: Katana Clash
author: Logan Stroud
navbar-links:
  Info: "aboutme"
  Resources:
    - Katana clash discord: "https://github.com/katanaclash/Katana-clash"
    - Katana clash roblox group: "placeholder.com"
    - Katana clash guide: "Placeholder.net"
  Author's home: "https://github.com/katanaclash"
avatar: "/assets/img/avatar-icon.png"
round-avatar: true
social-network-links:
  email: "stroudlo@ahcspatriots.us"
  github: stroudlo
  youtube: "@zmixinyt"
rss-description: This website is a virtual proof that I'm awesomesauce
share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false
navbar-var-length: false
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#5A5A5A"
text-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
date_format: "%B %-d, %Y"
timezone: "America/Boise"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true 
    scope:
      path: "" 
    values:
      layout: "page"
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap


